version: "3"
services:
  node:
      ports:
      - "80:80"
      build:
        dockerfile: Dockerfile
      working_dir: /var/www/app
      depends_on:
          - db
          - memcache
      volumes:
          - ./app:/var/www/app:cached

  db:
    image: mariadb:latest
    ports:
      - "33061:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker-stack
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 12345

  memcache:
    image: memcached:latest

volumes:
  mysql-volume:
